services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: tennis
      POSTGRES_PASSWORD: tennis
      POSTGRES_DB: tennis
    ports: 
      - "5433:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tennis"]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:7.4
    ports: 
      - "6379:6379"
volumes:
  dbdata: